<?php

namespace Minsal\SimagdBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ImgCtlProyeccionEstablecimientoAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Minsal\SimagdBundle\Controller\ImgCtlProyeccionEstablecimientoAdminController();
        return $instance;
    }
}
