services:
    minsal_simagd.admin.imagenologia_digital:
        class: Minsal\SimagdBundle\Admin\ImagenologiaDigitalAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgSolicitudEstudio, MinsalSimagdBundle:ImagenologiaDigitalAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: ID-1-SIMAGD, label: Inicio}

    minsal_simagd.admin.generacion_reporte_imagenologia:
        class: Minsal\SimagdBundle\Admin\GeneracionReporteImagenologiaAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgSolicitudEstudio, MinsalSimagdBundle:GeneracionReporteImagenologiaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    #NUEVA EXPLORACION
    minsal_simagd.admin.img_ctl_proyeccion:
        class: Minsal\SimagdBundle\Admin\RyxCtlProyeccionRadiologicaAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgCtlProyeccion, MinsalSimagdBundle:RyxCtlProyeccionRadiologicaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: CTI-1-Catalogos, label: Proyecciones}

    #EXPLORACIONES REALIZABLES
    minsal_simagd.admin.img_ctl_proyeccion_establecimiento:
        class: Minsal\SimagdBundle\Admin\RyxCtlProyeccionEstablecimientoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgCtlProyeccionEstablecimiento, MinsalSimagdBundle:RyxCtlProyeccionEstablecimientoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    #NUEVA MODALIDAD
    minsal_siaps.admin.ctl_area_servicio_diagnostico:
        class: Minsal\SiapsBundle\Admin\CtlAreaServicioDiagnosticoAdmin
        arguments: [~, Minsal\SiapsBundle\Entity\CtlAreaServicioDiagnostico, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: CTI-1-Catalogos, label: Modalidades}
        calls:
            - [setTemplate, [edit, MinsalSiapsBundle:CtlAreaServicioDiagnosticoAdmin:m_edit.html.twig]]

    #NUEVO EXAMEN
    minsal_siaps.admin.ctl_examen_servicio_diagnostico:
        class: Minsal\SiapsBundle\Admin\CtlExamenServicioDiagnosticoAdmin
        arguments: [~, Minsal\SiapsBundle\Entity\CtlExamenServicioDiagnostico, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: CTI-1-Catalogos, label: Exámenes}

    #NUEVO MNT REALIZABLE
    minsal_siaps.admin.mnt_area_examen_establecimiento:
        class: Minsal\SiapsBundle\Admin\MntAreaExamenEstablecimientoAdmin
        arguments: [~, Minsal\SiapsBundle\Entity\MntAreaExamenEstablecimiento, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: CTI-1-Catalogos, label: Exámenes Realizables}

    #admin para preinscripcion  Codigo 'PI' label Solicitud
    minsal_simagd.admin.img_solicitud_estudio:
        class: Minsal\SimagdBundle\Admin\RyxSolicitudEstudioAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgSolicitudEstudio, MinsalSimagdBundle:RyxSolicitudEstudioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: PI-1-Solicitud, label: Solicitudes}

    minsal_simagd.admin.img_solicitud_estudio_proyeccion:
        class: Minsal\SimagdBundle\Admin\RyxSolicitudEstudioProyeccionAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgSolicitudEstudioProyeccion, MinsalSimagdBundle:RyxSolicitudEstudioProyeccionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    #admin para solicitud de diagnostico  Codigo 'SD' label Diagnosticos
    minsal_simagd.admin.img_solicitud_diagnostico:
        class: Minsal\SimagdBundle\Admin\RyxSolicitudDiagnosticoPostEstudioAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgSolicitudDiagnostico, MinsalSimagdBundle:RyxSolicitudDiagnosticoPostEstudioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    #admin para citas  Codigo 'CI' label Citas de Imagenología
    minsal_simagd.admin.img_cita:
        class: Minsal\SimagdBundle\Admin\RyxCitaProgramadaAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgCita, MinsalSimagdBundle:RyxCitaProgramadaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: CI-1-Citas de Imagenología, label: Agenda}

    #admin para citas Codigo 'CI' label Citas de Imagenologia
    minsal_simagd.admin.img_ctl_configuracion_agenda:
        class: Minsal\SimagdBundle\Admin\RyxCtlConfiguracionAgendaAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgCtlConfiguracionAgenda, MinsalSimagdBundle:RyxCtlConfiguracionAgendaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    #CTL de PACS por Establecimiento
    minsal_simagd.admin.img_ctl_pacs_establecimiento:
        class: Minsal\SimagdBundle\Admin\RyxCtlConexionPacsEstablecimientoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgCtlPacsEstablecimiento, MinsalSimagdBundle:RyxCtlConexionPacsEstablecimientoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: CTI-1-Catalogos, label: Servidores PACS}

    minsal_simagd.admin.img_ctl_motor_bd:
        class: Minsal\SimagdBundle\Admin\RyxCtlMotorBdAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgCtlMotorBd, MinsalSimagdBundle:RyxCtlMotorBdAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: CTI-1-Catalogos, label: Motores de Base de Datos}

    #EXAMENES SIN REALIZAR
    minsal_simagd.admin.img_pendiente_realizacion:
        class: Minsal\SimagdBundle\Admin\RyxExamenPendienteRealizacionAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgPendienteRealizacion, MinsalSimagdBundle:RyxExamenPendienteRealizacionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: IM-1-Imagenes Médicas, label: Exámenes Pendientes}

    minsal_simagd.admin.img_mis_examenes_no_concluidos:
        class: Minsal\SimagdBundle\Admin\ImgMisExamenesNoConcluidosAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgPendienteRealizacion, MinsalSimagdBundle:ImgMisExamenesNoConcluidosAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    #admin para imagenes medicas Codigo 'IM' label Imagenes Medicas
    minsal_simagd.admin.img_procedimiento_realizado:
        class: Minsal\SimagdBundle\Admin\RyxProcedimientoRadiologicoRealizadoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgProcedimientoRealizado, MinsalSimagdBundle:RyxProcedimientoRadiologicoRealizadoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: IM-1-Imagenes Médicas, label: Exámenes Registrados}

    #admin para imagenes medicas Codigo 'IM' label Imagenes Medicas
    minsal_simagd.admin.img_estudio_paciente:
        class: Minsal\SimagdBundle\Admin\RyxEstudioPorImagenesAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgEstudioPaciente, MinsalSimagdBundle:RyxEstudioPorImagenesAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: IM-1-Imagenes Médicas, label: Búsqueda de estudios}

    #LISTA DE LECTURA
    minsal_simagd.admin.img_pendiente_lectura:
        class: Minsal\SimagdBundle\Admin\RyxEstudioPendienteLecturaAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgPendienteLectura, MinsalSimagdBundle:RyxEstudioPendienteLecturaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: DI-1-Diagnosticos, label: Lecturas Pendientes}

    minsal_simagd.admin.img_mis_lecturas_no_concluidas:
        class: Minsal\SimagdBundle\Admin\ImgMisLecturasNoConcluidasAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgPendienteLectura, MinsalSimagdBundle:ImgMisLecturasNoConcluidasAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    #INTERPRETAR ESTUDIO
    minsal_simagd.admin.img_lectura:
        class: Minsal\SimagdBundle\Admin\RyxLecturaRadiologicaAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgLectura, MinsalSimagdBundle:RyxLecturaRadiologicaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: DI-1-Diagnosticos, label: Resultados}

    minsal_simagd.admin.img_pendiente_transcripcion:
        class: Minsal\SimagdBundle\Admin\RyxLecturaPendienteTranscripcionAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgPendienteTranscripcion, MinsalSimagdBundle:RyxLecturaPendienteTranscripcionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: DI-1-Diagnosticos, label: Transcripciones Pendientes}

    minsal_simagd.admin.img_mis_transcripciones_no_concluidas:
        class: Minsal\SimagdBundle\Admin\ImgMisTranscripcionesNoConcluidasAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgPendienteTranscripcion, MinsalSimagdBundle:ImgMisTranscripcionesNoConcluidasAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    #TRANSCRIBIR DIAGNOSTICO
    minsal_simagd.admin.img_diagnostico:
        class: Minsal\SimagdBundle\Admin\RyxDiagnosticoRadiologicoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgDiagnostico, MinsalSimagdBundle:RyxDiagnosticoRadiologicoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    minsal_simagd.admin.busqueda_diagnostico:
        class: Minsal\SimagdBundle\Admin\BusquedaDiagnosticoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgDiagnostico, MinsalSimagdBundle:BusquedaDiagnosticoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    #PENDIENTES DE VALIDAR
    minsal_simagd.admin.img_pendiente_validacion:
        class: Minsal\SimagdBundle\Admin\RyxDiagnosticoPendienteValidacionAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgPendienteValidacion, MinsalSimagdBundle:RyxDiagnosticoPendienteValidacionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    #AGREGAR NOTAS
    minsal_simagd.admin.img_nota_diagnostico:
        class: Minsal\SimagdBundle\Admin\RyxDiagnosticoSegundaOpinionMedicaAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgNotaDiagnostico, MinsalSimagdBundle:RyxDiagnosticoSegundaOpinionMedicaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    minsal_seguimiento.admin.sec_historial_clinico:
        class: Minsal\SeguimientoBundle\Admin\SecHistorialClinicoAdmin
        arguments: [~, Minsal\SeguimientoBundle\Entity\SecHistorialClinico, MinsalSeguimientoBundle:SecHistorialClinicoAdmin]
        tags:
            # - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}
            - {name: sonata.admin, manager_type: orm, group: ID-1-SIMAGD, label: Historial Clínico}

    minsal_simagd.admin.img_material_utilizado:
        class: Minsal\SimagdBundle\Admin\RyxProcedimientoMaterialUtilizadoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgMaterialUtilizado, MinsalSimagdBundle:RyxProcedimientoMaterialUtilizadoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    minsal_simagd.admin.img_ctl_material_establecimiento:
        class: Minsal\SimagdBundle\Admin\RyxCtlMaterialEstablecimientoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgCtlMaterialEstablecimiento, MinsalSimagdBundle:RyxCtlMaterialEstablecimientoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    minsal_simagd.admin.img_ctl_material:
        class: Minsal\SimagdBundle\Admin\RyxCtlMaterialAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgCtlMaterial, MinsalSimagdBundle:RyxCtlMaterialAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: CTI-1-Catalogos, label: Materiales}

    minsal_simagd.admin.img_bloqueo_agenda:
        class: Minsal\SimagdBundle\Admin\RyxBloqueoAgendaAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\RyxBloqueoAgenda, MinsalSimagdBundle:RyxBloqueoAgendaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    minsal_simagd.admin.img_solicitud_estudio_complementario:
        class: Minsal\SimagdBundle\Admin\RyxSolicitudEstudioComplementarioAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgSolicitudEstudioComplementario, MinsalSimagdBundle:RyxSolicitudEstudioComplementarioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    minsal_simagd.admin.img_solicitud_estudio_complementario_proyeccion:
        class: Minsal\SimagdBundle\Admin\RyxSolicitudEstudioComplementarioProyeccionAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgSolicitudEstudioComplementarioProyeccion, MinsalSimagdBundle:RyxSolicitudEstudioComplementarioProyeccionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    minsal_simagd.admin.img_lectura_estudio:
        class: Minsal\SimagdBundle\Admin\RyxLecturaEstudioAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgLecturaEstudio, MinsalSimagdBundle:RyxLecturaEstudioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    minsal_simagd.admin.img_dato_autocomplemento:
        class: Minsal\SimagdBundle\Admin\RyxDatoAutocomplementoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgDatoAutocomplemento, MinsalSimagdBundle:RyxDatoAutocomplementoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    minsal_simagd.admin.img_ctl_patron_diagnostico:
        class: Minsal\SimagdBundle\Admin\RyxCtlPatronDiagnosticoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgCtlPatronDiagnostico, MinsalSimagdBundle:RyxCtlPatronDiagnosticoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: DI-1-Diagnosticos, label: Patrones de diagnóstico}

    minsal_simagd.admin.img_ctl_preparacion_estudio:
        class: Minsal\SimagdBundle\Admin\RyxCtlPreparacionEstudioAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgCtlPreparacionEstudio, MinsalSimagdBundle:RyxCtlPreparacionEstudioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: CI-1-Citas de Imagenología, label: Catálogo de Preparaciones para estudio}

    minsal_simagd.admin.img_solicitud_estudio_mamografia:
        class: Minsal\SimagdBundle\Admin\RyxSolicitudEstudioMamografiaAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgSolicitudEstudioMamografia, MinsalSimagdBundle:RyxSolicitudEstudioMamografiaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    minsal_simagd.admin.img_solicitud_estudio_mamografia_sintomatologia:
        class: Minsal\SimagdBundle\Admin\RyxSolicitudEstudioMamografiaSintomatologiaAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\ImgSolicitudEstudioMamografiaSintomatologia, MinsalSimagdBundle:RyxSolicitudEstudioMamografiaSintomatologiaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    minsal_simagd.admin.ctl_area_servicio_diagnostico:
        class: Minsal\SimagdBundle\Admin\CtlAreaServicioDiagnosticoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\CtlAreaServicioDiagnostico, MinsalSimagdBundle:CtlAreaServicioDiagnosticoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    minsal_simagd.admin.ctl_examen_servicio_diagnostico:
        class: Minsal\SimagdBundle\Admin\CtlExamenServicioDiagnosticoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\CtlExamenServicioDiagnostico, MinsalSimagdBundle:CtlExamenServicioDiagnosticoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}

    minsal_simagd.admin.mnt_area_examen_establecimiento:
        class: Minsal\SimagdBundle\Admin\MntAreaExamenEstablecimientoAdmin
        arguments: [~, Minsal\SimagdBundle\Entity\MntAreaExamenEstablecimiento, MinsalSimagdBundle:MntAreaExamenEstablecimientoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}
