<?php

namespace Minsal\SiapsBundle\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * ExamenServicioDiagnosticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenServicioDiagnosticoRepository extends EntityRepository
{
    /**
     * Método perteneciente a módulo <simagd>
     * @param type $idAtencion
     * @return type
     */
    public function obtenerExamenesImagenologia ($idAtencion )
    {
        $query = $this->getEntityManager()
                        ->createQueryBuilder()
                            ->select('exm')
                            ->from('MinsalSiapsBundle:CtlExamenServicioDiagnostico', 'exm')
                            ->where('exm.idAtencion = :id_atn')
                            ->setParameter('id_atn', $idAtencion)
                            ->orderBy('exm.idsexo')
                            ->addOrderBy('exm.descripcion')
                            ->distinct();
        
        return $query;
    }
    
    /**
     * Método perteneciente a módulo <simagd>
     * @param type $idAtencion
     * @return type
     */
    public function obtenerExamenesRealizablesLocal($idEstablecimiento, $idAtencion = '97' )
    {
        /** SubQuery */
        $subQuery = $this->getEntityManager()
                        ->createQueryBuilder()
                            ->select('mr')
                            ->from('MinsalSiapsBundle:MntAreaExamenEstablecimiento', 'mr')
                            ->where('exm.id = mr.idExamenServicioDiagnostico')
                            ->andWhere('mr.imgHabilitado = TRUE')
                            ->andWhere('mr.idEstablecimiento = :id_est');
                
        /** Query */
        $query = $this->getEntityManager()
                        ->createQueryBuilder()
                            ->select('exm')
                            ->from('MinsalSiapsBundle:CtlExamenServicioDiagnostico', 'exm')
                            ->andWhere('exm.idAtencion = :id_atn')
                            ->setParameter('id_atn', $idAtencion);
        
        $query->andWhere($query->expr()->exists($subQuery->getDql()))
                            ->setParameter('id_est', $idEstablecimiento);
        
        $query->orderBy('exm.idsexo')
                            ->addOrderBy('exm.descripcion');
                
        $query->distinct();
        
        return $query->getQuery()->getResult();
    }
}
