<?php

namespace Minsal\SimagdBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MntAreaExamenEstablecimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MntAreaExamenEstablecimientoRepository extends EntityRepository
{
    public function data($id_estab, $bs_filters = array())
    {
        $query = $this->getEntityManager()
                        ->createQueryBuilder('mr')
                            ->select('mr')
                            ->addSelect('exm')
                            ->addSelect('m')

                            ->addSelect('mr.id AS id, m.nombrearea AS modalidad, m.idarea AS codigo_modalidad, exm.descripcion AS examen, exm.idestandar as codigo_examen, mr.fechaHoraReg AS fecha_registro, mr.fechaHoraMod AS fecha_edicion, mr.imgHabilitado as habilitado')

                            // ->addSelect('IDENTITY(exm.idAtencion) AS exm_id_atencion')
                            // ->addSelect('usrRg.username AS expl_usernameUserReg, usrRg.id AS expl_id_userReg, usrMd.username AS expl_usernameUserMod, usrMd.id AS expl_id_userMod')
                            // ->addSelect('CONCAT(COALESCE(usrRgEmp.apellido, \'\'), \', \', COALESCE(usrRgEmp.nombre, \'\')) AS expl_nombreUserReg')
                            // ->addSelect('CASE WHEN (usrMd.username IS NOT NULL) THEN CONCAT(COALESCE(usrMdEmp.apellido, \'\'), \', \', COALESCE(usrMdEmp.nombre, \'\')) ELSE \'\' END AS expl_nombreUserMod')
                            // ->addSelect('CASE WHEN (sex.id IS NOT NULL) THEN sex.nombre ELSE \'Todos los sexos\' END AS exm_sexo')
                            ->from('MinsalSimagdBundle:MntAreaExamenEstablecimiento', 'mr')
                            ->innerJoin('mr.idExamenServicioDiagnostico', 'exm')
                            ->innerJoin('mr.idAreaServicioDiagnostico', 'm')
                            ->where('mr.idEstablecimiento = :id_est')
                            ->setParameter('id_est', $id_estab)
                            ->orderBy('m.idarea', 'DESC')
                            ->addOrderBy('exm.idestandar', 'DESC')
                            ->distinct();

        /*
         * --| add filters from BSTABLE_FILTER to query
         */
        $simagd_er_model    = $this->getEntityManager()->getRepository('MinsalSimagdBundle:ImgSolicitudEstudio');
        $apply_filters      = $simagd_er_model->getBsTableFiltersV2($query, $bs_filters);
        if ($apply_filters !== false)
        {
            $query->andWhere($apply_filters);
        }
        /*
         * |-- END filters from BSTABLE_FILTER to query
         */

        return $query->getQuery()->getScalarResult();
    }

}