<?php

namespace Minsal\SimagdBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrioridadAtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrioridadAtencionRepository extends EntityRepository
{
    public function obtenerPrioridadesAtencionV2($return = 'result')
    {
        $query = $this->getEntityManager()
                        ->createQueryBuilder('prAtn')
                            ->select('prAtn')
                            ->from('MinsalSimagdBundle:ImgCtlPrioridadAtencion', 'prAtn')
                            ->orderBy('prAtn.id', 'asc')
                            ->distinct();

	if($return == 'scalar')
	{
	    $query->addSelect('prAtn.id AS id, prAtn.nombre AS text, prAtn.codigo as cod, prAtn.estiloPresentacion as style');
	}

        return $return == 'query' ?
	    $query : ($return == 'scalar' ? $query->getQuery()->getScalarResult()
		: $query->getQuery()->getResult()
	    );
    }
    
}
