<?php

namespace Minsal\SimagdBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SolicitudEstudioMamografiaSintomatologiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudEstudioMamografiaSintomatologiaRepository extends EntityRepository
{
}
