<?php

namespace Minsal\SimagdBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SolicitudEstudioComplementarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudEstudioComplementarioRepository extends EntityRepository
{
    public function obtenerSolicitudesEstudioComplementario($id_estab, $bs_filters = array())
    {
        $query = $this->getEntityManager()
                        ->createQueryBuilder()
                            ->select('solcmpl')
                            ->from('MinsalSimagdBundle:ImgSolicitudEstudioComplementario', 'solcmpl')
                            ->innerJoin('solcmpl.idSolicitudEstudio', 'prc')
                            ->innerJoin('solcmpl.idEstudioPadre', 'est');

        $query->where($query->expr()->orx(
                            $query->expr()->eq('solcmpl.idEstablecimientoSolicitado', ':id_est_sol'),
                            $query->expr()->eq('prc.idEstablecimientoReferido', ':id_est_ref'),
                            $query->expr()->eq('prc.idEstablecimientoDiagnosticante', ':id_est_diag'),
                            $query->expr()->eq('est.idEstablecimiento', ':id_est')
                        ))
                            ->setParameter('id_est_sol', $id_estab)
                            ->setParameter('id_est_ref', $id_estab)
                            ->setParameter('id_est_diag', $id_estab)
                            ->setParameter('id_est', $id_estab);
        
        $query->orderBy('solcmpl.fechaSolicitud', 'desc')
                            ->addOrderBy('solcmpl.id', 'desc');
                
        $query->distinct();
        
        return $query->getQuery()->getResult();
    }

    public function obtenerSolicitudesEstudioComplementarioV2($id_estab, $bs_filters = array())
    {
        $query = $this->getEntityManager()
                        ->createQueryBuilder('solcmpl')
                            ->select('solcmpl')
                            ->addSelect('est')
                            ->addSelect('statusSc')
                            ->addSelect('explocal')->addSelect('unknExp')
                            ->addSelect('prAtn')

                            ->addSelect('solcmpl.id AS id, stdroot.nombre AS origen, CONCAT(pct.primerApellido, \' \', COALESCE(pct.segundoApellido, \'\'), \', \', pct.primerNombre, \' \', COALESCE(pct.segundoNombre, \'\')) AS paciente, explocal.numero AS numero_expediente, CASE WHEN (empcmpl.id IS NOT NULL) THEN CONCAT(COALESCE(empcmpl.apellido, \'\'), \', \', COALESCE(empcmpl.nombre, \'\')) ELSE \'\' END AS medico, ar.nombre AS area_atencion, atn.nombre AS atencion, m.nombrearea as modalidad, prAtn.nombre AS triage, solcmpl.fechaSolicitud as fecha_solicitud')

                            ->addSelect('prc.fechaCreacion AS prc_fechaCreacion, prz.fechaAlmacenado AS prz_fechaAlmacenado')
                            ->addSelect('CONCAT(pct.primerApellido, \' \', COALESCE(pct.segundoApellido, \'\'), \', \', pct.primerNombre, \' \', COALESCE(pct.segundoNombre, \'\')) AS prc_paciente')
                            ->addSelect('stdroot.nombre AS prc_origen, stdroot.id AS prc_id_origen, ar.nombre AS prc_areaAtencion, ar.id AS prc_id_areaAtencion, atn.nombre AS prc_atencion, atn.id AS prc_id_atencion')
                            ->addSelect('CONCAT(COALESCE(empprc.apellido, \'\'), \', \', COALESCE(empprc.nombre, \'\')) AS prc_solicitante')
                            ->addSelect('CONCAT(COALESCE(empcmpl.apellido, \'\'), \', \', COALESCE(empcmpl.nombre, \'\')) AS solcmpl_solicitante, empcmpl.id AS solcmpl_id_solicitante, tpEmp.tipo as solcmpl_tipoEmpleado')
                            ->addSelect('stdref.nombre AS prc_referido, stdref.id AS prc_id_referido, stdiag.nombre AS prc_diagnosticante, stdiag.id AS prc_id_diagnosticante, stdcmpl.nombre AS solcmpl_solicitado, stdcmpl.id AS solcmpl_id_solicitado')
                            ->addSelect('m.nombrearea AS prc_modalidad, m.id AS prc_id_modalidad, prAtn.nombre AS solcmpl_prioridadAtencion, prAtn.id AS solcmpl_id_prioridad, prAtn.codigo as solcmpl_codigoPrioridad, mcmpl.nombrearea as solcmpl_modalidad, mcmpl.id AS solcmpl_id_modalidad')
                            ->addSelect('usrRg.username as solcmpl_usernameUserReg, usrRg.id AS solcmpl_id_userReg')
                            ->addSelect('CONCAT(COALESCE(usrRgEmp.apellido, \'\'), \', \', COALESCE(usrRgEmp.nombre, \'\')) AS solcmpl_nombreUserReg')
                            ->addSelect('CASE WHEN (tcnlprz.id IS NOT NULL) THEN CONCAT(COALESCE(tcnlprz.apellido, \'\'), \', \', COALESCE(tcnlprz.nombre, \'\')) ELSE \'\' END AS prz_tecnologo')
                            ->from('MinsalSimagdBundle:ImgSolicitudEstudioComplementario', 'solcmpl')
                            ->leftJoin('solcmpl.idSolicitudEstudio', 'prc')
                            ->innerJoin('solcmpl.idEstudioPadre', 'est')
                            ->innerJoin('solcmpl.idAreaServicioDiagnostico', 'mcmpl')
                            ->leftJoin('solcmpl.idRadiologoSolicita', 'empcmpl')
                            ->innerJoin('est.idProcedimientoRealizado', 'prz')
                            ->innerJoin('prz.idTecnologoRealiza', 'tcnlprz')
                            ->innerJoin('solcmpl.idUserReg', 'usrRg')
                            ->leftJoin('prc.idAtenAreaModEstab', 'aams')
                            ->leftJoin('prc.idEmpleado', 'empprc')
                            ->leftJoin('prc.idExpediente', 'exp')
                            ->leftJoin('prc.idAreaServicioDiagnostico', 'm')
                            ->leftJoin('prc.idEstablecimientoReferido', 'stdref')
                            ->leftJoin('prc.idEstablecimientoDiagnosticante', 'stdiag')
                            ->leftJoin('solcmpl.idEstablecimientoSolicitado', 'stdcmpl')
                            ->leftJoin('solcmpl.idPrioridadAtencion', 'prAtn')
                            ->leftJoin('prc.idFormaContacto', 'frCt')
                            ->leftJoin('prc.idContactoPaciente', 'ctPct')
                            ->leftJoin('aams.idAtencion', 'atn')
                            ->leftJoin('aams.idAreaModEstab', 'ams')
                            ->leftJoin('aams.idEstablecimiento', 'stdroot')
                            ->leftJoin('ams.idAreaAtencion', 'ar')
                            ->leftJoin('exp.idPaciente', 'pct')
                            ->innerJoin('usrRg.idEmpleado', 'usrRgEmp')
                            ->leftJoin('empcmpl.idTipoEmpleado', 'tpEmp')
                            ->leftJoin('solcmpl.idEstadoSolicitud', 'statusSc');
        
        $query->leftJoin('prc.idExpedienteFicticio', 'unknExp')->leftJoin('MinsalSiapsBundle:MntExpediente', 'explocal',
                                    \Doctrine\ORM\Query\Expr\Join::WITH,
                                            $query->expr()->andx(
                                                $query->expr()->eq('pct.id', 'explocal.idPaciente'),
                                                $query->expr()->eq('explocal.idEstablecimiento', ':id_est_explocal')
                                            )
                            )
                            ->setParameter('id_est_explocal', $id_estab);

        $query->where($query->expr()->orx(
                            $query->expr()->eq('solcmpl.idEstablecimientoSolicitado', ':id_est_sol'),
                            $query->expr()->eq('prc.idEstablecimientoReferido', ':id_est_ref'),
                            $query->expr()->eq('prc.idEstablecimientoDiagnosticante', ':id_est_diag'),
                            $query->expr()->eq('est.idEstablecimiento', ':id_est')
                        ))
                            ->setParameter('id_est_sol', $id_estab)
                            ->setParameter('id_est_ref', $id_estab)
                            ->setParameter('id_est_diag', $id_estab)
                            ->setParameter('id_est', $id_estab);
        
        $query->orderBy('solcmpl.fechaSolicitud', 'desc')
                            ->addOrderBy('solcmpl.id', 'desc')
                            ->distinct();
        
        /*
         * --| add filters from BSTABLE_FILTER to query
         */
        $simagd_er_model    = $this->getEntityManager()->getRepository('MinsalSimagdBundle:ImgSolicitudEstudio');
        $apply_filters      = $simagd_er_model->getBsTableFiltersV2($query, $bs_filters);
        if ($apply_filters !== false)
        {
            $query->andWhere($apply_filters);
        }
        /*
         * |-- END filters from BSTABLE_FILTER to query
         */

        return $query->getQuery()->getScalarResult();
    }
    
}
