<?php

namespace Minsal\SimagdBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ImgCtlMotorBdAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Minsal\SimagdBundle\Controller\ImgCtlMotorBdAdminController();
        return $instance;
    }
}
