<?php

namespace Proxies\__CG__\Minsal\SiapsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MntRangohora extends \Minsal\SiapsBundle\Entity\MntRangohora implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'horaIni', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'horaFin', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'modulo', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'idusuarioreg', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'fechahorareg', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'meridianoini', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'meridianofin');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'id', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'horaIni', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'horaFin', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'modulo', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'idusuarioreg', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'fechahorareg', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'meridianoini', '' . "\0" . 'Minsal\\SiapsBundle\\Entity\\MntRangohora' . "\0" . 'meridianofin');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MntRangohora $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraIni($horaIni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraIni', array($horaIni));

        return parent::setHoraIni($horaIni);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraIni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraIni', array());

        return parent::getHoraIni();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraFin($horaFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraFin', array($horaFin));

        return parent::setHoraFin($horaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraFin', array());

        return parent::getHoraFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setModulo($modulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModulo', array($modulo));

        return parent::setModulo($modulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getModulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModulo', array());

        return parent::getModulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechahorareg($fechahorareg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechahorareg', array($fechahorareg));

        return parent::setFechahorareg($fechahorareg);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechahorareg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechahorareg', array());

        return parent::getFechahorareg();
    }

    /**
     * {@inheritDoc}
     */
    public function setMeridianoini($meridianoini)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeridianoini', array($meridianoini));

        return parent::setMeridianoini($meridianoini);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeridianoini()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeridianoini', array());

        return parent::getMeridianoini();
    }

    /**
     * {@inheritDoc}
     */
    public function setMeridianofin($meridianofin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeridianofin', array($meridianofin));

        return parent::setMeridianofin($meridianofin);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeridianofin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeridianofin', array());

        return parent::getMeridianofin();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuarioreg(\Application\Sonata\UserBundle\Entity\User $idusuarioreg = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuarioreg', array($idusuarioreg));

        return parent::setIdusuarioreg($idusuarioreg);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuarioreg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuarioreg', array());

        return parent::getIdusuarioreg();
    }

}
