<?php

namespace Proxies\__CG__\Minsal\SimagdBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ImgCtlSubgrupoMaterial extends \Minsal\SimagdBundle\Entity\ImgCtlSubgrupoMaterial implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgCtlSubgrupoMaterial' . "\0" . 'id', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgCtlSubgrupoMaterial' . "\0" . 'nombre', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgCtlSubgrupoMaterial' . "\0" . 'codigo', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgCtlSubgrupoMaterial' . "\0" . 'descripcion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgCtlSubgrupoMaterial' . "\0" . 'idGrupoMaterial', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgCtlSubgrupoMaterial' . "\0" . 'subgrupoMateriales');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgCtlSubgrupoMaterial' . "\0" . 'id', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgCtlSubgrupoMaterial' . "\0" . 'nombre', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgCtlSubgrupoMaterial' . "\0" . 'codigo', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgCtlSubgrupoMaterial' . "\0" . 'descripcion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgCtlSubgrupoMaterial' . "\0" . 'idGrupoMaterial', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgCtlSubgrupoMaterial' . "\0" . 'subgrupoMateriales');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ImgCtlSubgrupoMaterial $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', array($codigo));

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', array());

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGrupoMaterial(\Minsal\SimagdBundle\Entity\ImgCtlGrupoMaterial $idGrupoMaterial = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGrupoMaterial', array($idGrupoMaterial));

        return parent::setIdGrupoMaterial($idGrupoMaterial);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdGrupoMaterial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGrupoMaterial', array());

        return parent::getIdGrupoMaterial();
    }

    /**
     * {@inheritDoc}
     */
    public function addSubgrupoMateriale(\Minsal\SimagdBundle\Entity\ImgCtlMaterial $subgrupoMateriales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSubgrupoMateriale', array($subgrupoMateriales));

        return parent::addSubgrupoMateriale($subgrupoMateriales);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSubgrupoMateriale(\Minsal\SimagdBundle\Entity\ImgCtlMaterial $subgrupoMateriales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSubgrupoMateriale', array($subgrupoMateriales));

        return parent::removeSubgrupoMateriale($subgrupoMateriales);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubgrupoMateriales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubgrupoMateriales', array());

        return parent::getSubgrupoMateriales();
    }

}
