<?php

namespace Proxies\__CG__\Minsal\SimagdBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ImgBloqueoAgenda extends \Minsal\SimagdBundle\Entity\ImgBloqueoAgenda implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'id', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'fechaCreacion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'titulo', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'descripcion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'diaCompleto', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'fechaInicio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'fechaFin', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'horaInicio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'horaFin', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'color', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'fechaUltimaEdicion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'idAreaServicioDiagnostico', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'idEmpleadoRegistra', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'idRadiologoBloqueo', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'idUserMod', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'idUserReg', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'bloqueoExclusionesBloqueo');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'id', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'fechaCreacion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'titulo', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'descripcion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'diaCompleto', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'fechaInicio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'fechaFin', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'horaInicio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'horaFin', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'color', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'fechaUltimaEdicion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'idAreaServicioDiagnostico', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'idEmpleadoRegistra', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'idRadiologoBloqueo', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'idUserMod', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'idUserReg', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgBloqueoAgenda' . "\0" . 'bloqueoExclusionesBloqueo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ImgBloqueoAgenda $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiaCompleto($diaCompleto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiaCompleto', array($diaCompleto));

        return parent::setDiaCompleto($diaCompleto);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiaCompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiaCompleto', array());

        return parent::getDiaCompleto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaInicio($fechaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaInicio', array($fechaInicio));

        return parent::setFechaInicio($fechaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInicio', array());

        return parent::getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFin($fechaFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFin', array($fechaFin));

        return parent::setFechaFin($fechaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFin', array());

        return parent::getFechaFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraInicio($horaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraInicio', array($horaInicio));

        return parent::setHoraInicio($horaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraInicio', array());

        return parent::getHoraInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraFin($horaFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraFin', array($horaFin));

        return parent::setHoraFin($horaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraFin', array());

        return parent::getHoraFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setColor($color)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', array($color));

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', array());

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaUltimaEdicion($fechaUltimaEdicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaUltimaEdicion', array($fechaUltimaEdicion));

        return parent::setFechaUltimaEdicion($fechaUltimaEdicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaUltimaEdicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaUltimaEdicion', array());

        return parent::getFechaUltimaEdicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAreaServicioDiagnostico(\Minsal\SiapsBundle\Entity\CtlAreaServicioDiagnostico $idAreaServicioDiagnostico = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAreaServicioDiagnostico', array($idAreaServicioDiagnostico));

        return parent::setIdAreaServicioDiagnostico($idAreaServicioDiagnostico);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAreaServicioDiagnostico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAreaServicioDiagnostico', array());

        return parent::getIdAreaServicioDiagnostico();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEmpleadoRegistra(\Minsal\SiapsBundle\Entity\MntEmpleado $idEmpleadoRegistra = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEmpleadoRegistra', array($idEmpleadoRegistra));

        return parent::setIdEmpleadoRegistra($idEmpleadoRegistra);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEmpleadoRegistra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEmpleadoRegistra', array());

        return parent::getIdEmpleadoRegistra();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstablecimiento(\Minsal\SiapsBundle\Entity\CtlEstablecimiento $idEstablecimiento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstablecimiento', array($idEstablecimiento));

        return parent::setIdEstablecimiento($idEstablecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstablecimiento', array());

        return parent::getIdEstablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRadiologoBloqueo(\Minsal\SiapsBundle\Entity\MntEmpleado $idRadiologoBloqueo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRadiologoBloqueo', array($idRadiologoBloqueo));

        return parent::setIdRadiologoBloqueo($idRadiologoBloqueo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRadiologoBloqueo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRadiologoBloqueo', array());

        return parent::getIdRadiologoBloqueo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUserMod(\Application\Sonata\UserBundle\Entity\User $idUserMod = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUserMod', array($idUserMod));

        return parent::setIdUserMod($idUserMod);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUserMod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUserMod', array());

        return parent::getIdUserMod();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUserReg(\Application\Sonata\UserBundle\Entity\User $idUserReg = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUserReg', array($idUserReg));

        return parent::setIdUserReg($idUserReg);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUserReg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUserReg', array());

        return parent::getIdUserReg();
    }

    /**
     * {@inheritDoc}
     */
    public function addBloqueoExclusionesBloqueo(\Minsal\SimagdBundle\Entity\ImgExclusionBloqueo $bloqueoExclusionesBloqueo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBloqueoExclusionesBloqueo', array($bloqueoExclusionesBloqueo));

        return parent::addBloqueoExclusionesBloqueo($bloqueoExclusionesBloqueo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBloqueoExclusionesBloqueo(\Minsal\SimagdBundle\Entity\ImgExclusionBloqueo $bloqueoExclusionesBloqueo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBloqueoExclusionesBloqueo', array($bloqueoExclusionesBloqueo));

        return parent::removeBloqueoExclusionesBloqueo($bloqueoExclusionesBloqueo);
    }

    /**
     * {@inheritDoc}
     */
    public function getBloqueoExclusionesBloqueo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBloqueoExclusionesBloqueo', array());

        return parent::getBloqueoExclusionesBloqueo();
    }

}
