<?php

namespace Proxies\__CG__\Minsal\SimagdBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ImgEstudioPaciente extends \Minsal\SimagdBundle\Entity\ImgEstudioPaciente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'id', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'fechaEstudio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioUid', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'seriesUid', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'servidor', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'url', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'eliminadoEnPacs', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'idEstudioPadre', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'idExpediente', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'idExpedienteFicticio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'idProcedimientoRealizado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioEstudiosComplementarios', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioSolicitudesDiagnostico', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioLecturasRealizadas', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioLecturaEstudio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioPendienteLectura', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioEstudiosConsecuentes');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'id', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'fechaEstudio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioUid', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'seriesUid', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'servidor', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'url', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'eliminadoEnPacs', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'idEstudioPadre', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'idExpediente', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'idExpedienteFicticio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'idProcedimientoRealizado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioEstudiosComplementarios', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioSolicitudesDiagnostico', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioLecturasRealizadas', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioLecturaEstudio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioPendienteLectura', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgEstudioPaciente' . "\0" . 'estudioEstudiosConsecuentes');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ImgEstudioPaciente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEstudio($fechaEstudio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEstudio', array($fechaEstudio));

        return parent::setFechaEstudio($fechaEstudio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEstudio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEstudio', array());

        return parent::getFechaEstudio();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstudioUid($estudioUid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstudioUid', array($estudioUid));

        return parent::setEstudioUid($estudioUid);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstudioUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstudioUid', array());

        return parent::getEstudioUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesUid($seriesUid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesUid', array($seriesUid));

        return parent::setSeriesUid($seriesUid);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesUid', array());

        return parent::getSeriesUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setServidor($servidor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServidor', array($servidor));

        return parent::setServidor($servidor);
    }

    /**
     * {@inheritDoc}
     */
    public function getServidor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServidor', array());

        return parent::getServidor();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setEliminadoEnPacs($eliminadoEnPacs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEliminadoEnPacs', array($eliminadoEnPacs));

        return parent::setEliminadoEnPacs($eliminadoEnPacs);
    }

    /**
     * {@inheritDoc}
     */
    public function getEliminadoEnPacs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEliminadoEnPacs', array());

        return parent::getEliminadoEnPacs();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstablecimiento(\Minsal\SiapsBundle\Entity\CtlEstablecimiento $idEstablecimiento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstablecimiento', array($idEstablecimiento));

        return parent::setIdEstablecimiento($idEstablecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstablecimiento', array());

        return parent::getIdEstablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstudioPadre(\Minsal\SimagdBundle\Entity\ImgEstudioPaciente $idEstudioPadre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstudioPadre', array($idEstudioPadre));

        return parent::setIdEstudioPadre($idEstudioPadre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstudioPadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstudioPadre', array());

        return parent::getIdEstudioPadre();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdExpediente(\Minsal\SiapsBundle\Entity\MntExpediente $idExpediente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdExpediente', array($idExpediente));

        return parent::setIdExpediente($idExpediente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdExpediente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdExpediente', array());

        return parent::getIdExpediente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdExpedienteFicticio(\Minsal\SimagdBundle\Entity\ImgExpedienteFicticio $idExpedienteFicticio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdExpedienteFicticio', array($idExpedienteFicticio));

        return parent::setIdExpedienteFicticio($idExpedienteFicticio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdExpedienteFicticio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdExpedienteFicticio', array());

        return parent::getIdExpedienteFicticio();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProcedimientoRealizado(\Minsal\SimagdBundle\Entity\ImgProcedimientoRealizado $idProcedimientoRealizado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProcedimientoRealizado', array($idProcedimientoRealizado));

        return parent::setIdProcedimientoRealizado($idProcedimientoRealizado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProcedimientoRealizado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProcedimientoRealizado', array());

        return parent::getIdProcedimientoRealizado();
    }

    /**
     * {@inheritDoc}
     */
    public function addEstudioEstudiosComplementario(\Minsal\SimagdBundle\Entity\ImgSolicitudEstudioComplementario $estudioEstudiosComplementarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEstudioEstudiosComplementario', array($estudioEstudiosComplementarios));

        return parent::addEstudioEstudiosComplementario($estudioEstudiosComplementarios);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEstudioEstudiosComplementario(\Minsal\SimagdBundle\Entity\ImgSolicitudEstudioComplementario $estudioEstudiosComplementarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEstudioEstudiosComplementario', array($estudioEstudiosComplementarios));

        return parent::removeEstudioEstudiosComplementario($estudioEstudiosComplementarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstudioEstudiosComplementarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstudioEstudiosComplementarios', array());

        return parent::getEstudioEstudiosComplementarios();
    }

    /**
     * {@inheritDoc}
     */
    public function addEstudioSolicitudesDiagnostico(\Minsal\SimagdBundle\Entity\ImgSolicitudDiagnostico $estudioSolicitudesDiagnostico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEstudioSolicitudesDiagnostico', array($estudioSolicitudesDiagnostico));

        return parent::addEstudioSolicitudesDiagnostico($estudioSolicitudesDiagnostico);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEstudioSolicitudesDiagnostico(\Minsal\SimagdBundle\Entity\ImgSolicitudDiagnostico $estudioSolicitudesDiagnostico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEstudioSolicitudesDiagnostico', array($estudioSolicitudesDiagnostico));

        return parent::removeEstudioSolicitudesDiagnostico($estudioSolicitudesDiagnostico);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstudioSolicitudesDiagnostico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstudioSolicitudesDiagnostico', array());

        return parent::getEstudioSolicitudesDiagnostico();
    }

    /**
     * {@inheritDoc}
     */
    public function addEstudioLecturasRealizada(\Minsal\SimagdBundle\Entity\ImgLectura $estudioLecturasRealizadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEstudioLecturasRealizada', array($estudioLecturasRealizadas));

        return parent::addEstudioLecturasRealizada($estudioLecturasRealizadas);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEstudioLecturasRealizada(\Minsal\SimagdBundle\Entity\ImgLectura $estudioLecturasRealizadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEstudioLecturasRealizada', array($estudioLecturasRealizadas));

        return parent::removeEstudioLecturasRealizada($estudioLecturasRealizadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstudioLecturasRealizadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstudioLecturasRealizadas', array());

        return parent::getEstudioLecturasRealizadas();
    }

    /**
     * {@inheritDoc}
     */
    public function addEstudioLecturaEstudio(\Minsal\SimagdBundle\Entity\ImgLecturaEstudio $estudioLecturaEstudio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEstudioLecturaEstudio', array($estudioLecturaEstudio));

        return parent::addEstudioLecturaEstudio($estudioLecturaEstudio);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEstudioLecturaEstudio(\Minsal\SimagdBundle\Entity\ImgLecturaEstudio $estudioLecturaEstudio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEstudioLecturaEstudio', array($estudioLecturaEstudio));

        return parent::removeEstudioLecturaEstudio($estudioLecturaEstudio);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstudioLecturaEstudio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstudioLecturaEstudio', array());

        return parent::getEstudioLecturaEstudio();
    }

    /**
     * {@inheritDoc}
     */
    public function addEstudioPendienteLectura(\Minsal\SimagdBundle\Entity\ImgPendienteLectura $estudioPendienteLectura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEstudioPendienteLectura', array($estudioPendienteLectura));

        return parent::addEstudioPendienteLectura($estudioPendienteLectura);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEstudioPendienteLectura(\Minsal\SimagdBundle\Entity\ImgPendienteLectura $estudioPendienteLectura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEstudioPendienteLectura', array($estudioPendienteLectura));

        return parent::removeEstudioPendienteLectura($estudioPendienteLectura);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstudioPendienteLectura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstudioPendienteLectura', array());

        return parent::getEstudioPendienteLectura();
    }

    /**
     * {@inheritDoc}
     */
    public function addEstudioEstudiosConsecuente(\Minsal\SimagdBundle\Entity\ImgEstudioPaciente $estudioEstudiosConsecuentes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEstudioEstudiosConsecuente', array($estudioEstudiosConsecuentes));

        return parent::addEstudioEstudiosConsecuente($estudioEstudiosConsecuentes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEstudioEstudiosConsecuente(\Minsal\SimagdBundle\Entity\ImgEstudioPaciente $estudioEstudiosConsecuentes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEstudioEstudiosConsecuente', array($estudioEstudiosConsecuentes));

        return parent::removeEstudioEstudiosConsecuente($estudioEstudiosConsecuentes);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstudioEstudiosConsecuentes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstudioEstudiosConsecuentes', array());

        return parent::getEstudioEstudiosConsecuentes();
    }

}
