<?php

namespace Proxies\__CG__\Minsal\SimagdBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ImgPendienteRealizacion extends \Minsal\SimagdBundle\Entity\ImgPendienteRealizacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'id', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'fechaIngresoLista', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'esEmergencia', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'esComplementario', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idCitaProgramada', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idProcedimientoIniciado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idRegistraEmergencia', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idSolicitudEstudioComplementario', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idSolicitudEstudio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idTecnologoAsignado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idAsignaExaminante');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'id', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'fechaIngresoLista', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'esEmergencia', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'esComplementario', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idCitaProgramada', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idEstablecimiento', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idProcedimientoIniciado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idRegistraEmergencia', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idSolicitudEstudioComplementario', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idSolicitudEstudio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idTecnologoAsignado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgPendienteRealizacion' . "\0" . 'idAsignaExaminante');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ImgPendienteRealizacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaIngresoLista($fechaIngresoLista)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaIngresoLista', array($fechaIngresoLista));

        return parent::setFechaIngresoLista($fechaIngresoLista);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaIngresoLista()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaIngresoLista', array());

        return parent::getFechaIngresoLista();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsEmergencia($esEmergencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsEmergencia', array($esEmergencia));

        return parent::setEsEmergencia($esEmergencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsEmergencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsEmergencia', array());

        return parent::getEsEmergencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsComplementario($esComplementario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsComplementario', array($esComplementario));

        return parent::setEsComplementario($esComplementario);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsComplementario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsComplementario', array());

        return parent::getEsComplementario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCitaProgramada(\Minsal\SimagdBundle\Entity\ImgCita $idCitaProgramada = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCitaProgramada', array($idCitaProgramada));

        return parent::setIdCitaProgramada($idCitaProgramada);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCitaProgramada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCitaProgramada', array());

        return parent::getIdCitaProgramada();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstablecimiento(\Minsal\SiapsBundle\Entity\CtlEstablecimiento $idEstablecimiento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstablecimiento', array($idEstablecimiento));

        return parent::setIdEstablecimiento($idEstablecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstablecimiento', array());

        return parent::getIdEstablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProcedimientoIniciado(\Minsal\SimagdBundle\Entity\ImgProcedimientoRealizado $idProcedimientoIniciado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProcedimientoIniciado', array($idProcedimientoIniciado));

        return parent::setIdProcedimientoIniciado($idProcedimientoIniciado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProcedimientoIniciado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProcedimientoIniciado', array());

        return parent::getIdProcedimientoIniciado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRegistraEmergencia(\Minsal\SiapsBundle\Entity\MntEmpleado $idRegistraEmergencia = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRegistraEmergencia', array($idRegistraEmergencia));

        return parent::setIdRegistraEmergencia($idRegistraEmergencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRegistraEmergencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRegistraEmergencia', array());

        return parent::getIdRegistraEmergencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSolicitudEstudioComplementario(\Minsal\SimagdBundle\Entity\ImgSolicitudEstudioComplementario $idSolicitudEstudioComplementario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSolicitudEstudioComplementario', array($idSolicitudEstudioComplementario));

        return parent::setIdSolicitudEstudioComplementario($idSolicitudEstudioComplementario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSolicitudEstudioComplementario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSolicitudEstudioComplementario', array());

        return parent::getIdSolicitudEstudioComplementario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSolicitudEstudio(\Minsal\SimagdBundle\Entity\ImgSolicitudEstudio $idSolicitudEstudio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSolicitudEstudio', array($idSolicitudEstudio));

        return parent::setIdSolicitudEstudio($idSolicitudEstudio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSolicitudEstudio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSolicitudEstudio', array());

        return parent::getIdSolicitudEstudio();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTecnologoAsignado(\Minsal\SiapsBundle\Entity\MntEmpleado $idTecnologoAsignado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTecnologoAsignado', array($idTecnologoAsignado));

        return parent::setIdTecnologoAsignado($idTecnologoAsignado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTecnologoAsignado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTecnologoAsignado', array());

        return parent::getIdTecnologoAsignado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAsignaExaminante(\Minsal\SiapsBundle\Entity\MntEmpleado $idAsignaExaminante = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAsignaExaminante', array($idAsignaExaminante));

        return parent::setIdAsignaExaminante($idAsignaExaminante);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAsignaExaminante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAsignaExaminante', array());

        return parent::getIdAsignaExaminante();
    }

}
