<?php

namespace Proxies\__CG__\Minsal\SimagdBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ImgSolicitudDiagnostico extends \Minsal\SimagdBundle\Entity\ImgSolicitudDiagnostico implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'id', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'solicitudRemota', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'fechaCreacion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'justificacion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'fechaProximaConsulta', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'observaciones', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'idEmpleado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'idEstablecimientoSolicitado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'idEstadoSolicitud', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'idEstudio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'idSolicitudEstudio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'idUserReg');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'id', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'solicitudRemota', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'fechaCreacion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'justificacion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'fechaProximaConsulta', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'observaciones', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'idEmpleado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'idEstablecimientoSolicitado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'idEstadoSolicitud', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'idEstudio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'idSolicitudEstudio', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgSolicitudDiagnostico' . "\0" . 'idUserReg');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ImgSolicitudDiagnostico $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolicitudRemota($solicitudRemota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolicitudRemota', array($solicitudRemota));

        return parent::setSolicitudRemota($solicitudRemota);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitudRemota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitudRemota', array());

        return parent::getSolicitudRemota();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setJustificacion($justificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJustificacion', array($justificacion));

        return parent::setJustificacion($justificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getJustificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJustificacion', array());

        return parent::getJustificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaProximaConsulta($fechaProximaConsulta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaProximaConsulta', array($fechaProximaConsulta));

        return parent::setFechaProximaConsulta($fechaProximaConsulta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaProximaConsulta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaProximaConsulta', array());

        return parent::getFechaProximaConsulta();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', array($observaciones));

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', array());

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEmpleado(\Minsal\SiapsBundle\Entity\MntEmpleado $idEmpleado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEmpleado', array($idEmpleado));

        return parent::setIdEmpleado($idEmpleado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEmpleado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEmpleado', array());

        return parent::getIdEmpleado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstablecimientoSolicitado(\Minsal\SiapsBundle\Entity\CtlEstablecimiento $idEstablecimientoSolicitado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstablecimientoSolicitado', array($idEstablecimientoSolicitado));

        return parent::setIdEstablecimientoSolicitado($idEstablecimientoSolicitado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstablecimientoSolicitado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstablecimientoSolicitado', array());

        return parent::getIdEstablecimientoSolicitado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstadoSolicitud(\Minsal\SimagdBundle\Entity\ImgCtlEstadoSolicitud $idEstadoSolicitud = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstadoSolicitud', array($idEstadoSolicitud));

        return parent::setIdEstadoSolicitud($idEstadoSolicitud);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstadoSolicitud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstadoSolicitud', array());

        return parent::getIdEstadoSolicitud();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstudio(\Minsal\SimagdBundle\Entity\ImgEstudioPaciente $idEstudio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstudio', array($idEstudio));

        return parent::setIdEstudio($idEstudio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstudio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstudio', array());

        return parent::getIdEstudio();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSolicitudEstudio(\Minsal\SimagdBundle\Entity\ImgSolicitudEstudio $idSolicitudEstudio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSolicitudEstudio', array($idSolicitudEstudio));

        return parent::setIdSolicitudEstudio($idSolicitudEstudio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSolicitudEstudio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSolicitudEstudio', array());

        return parent::getIdSolicitudEstudio();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUserReg(\Application\Sonata\UserBundle\Entity\User $idUserReg = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUserReg', array($idUserReg));

        return parent::setIdUserReg($idUserReg);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUserReg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUserReg', array());

        return parent::getIdUserReg();
    }

}
