<?php

namespace Proxies\__CG__\Minsal\SimagdBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ImgDiagnostico extends \Minsal\SimagdBundle\Entity\ImgDiagnostico implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'id', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'hallazgos', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'conclusion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'fechaTranscrito', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'fechaCorregido', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'fechaAprobado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'errores', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'incidencias', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'observaciones', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'recomendaciones', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'fechaRegistro', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idEmpleado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idEstadoDiagnostico', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idLectura', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idPatronAplicado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idRadiologoAprueba', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idUserMod', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idUserReg', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'notasDiagnostico', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'diagnosticoPendienteValidar');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'id', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'hallazgos', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'conclusion', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'fechaTranscrito', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'fechaCorregido', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'fechaAprobado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'errores', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'incidencias', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'observaciones', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'recomendaciones', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'fechaRegistro', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idEmpleado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idEstadoDiagnostico', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idLectura', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idPatronAplicado', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idRadiologoAprueba', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idUserMod', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'idUserReg', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'notasDiagnostico', '' . "\0" . 'Minsal\\SimagdBundle\\Entity\\ImgDiagnostico' . "\0" . 'diagnosticoPendienteValidar');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ImgDiagnostico $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHallazgos($hallazgos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHallazgos', array($hallazgos));

        return parent::setHallazgos($hallazgos);
    }

    /**
     * {@inheritDoc}
     */
    public function getHallazgos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHallazgos', array());

        return parent::getHallazgos();
    }

    /**
     * {@inheritDoc}
     */
    public function setConclusion($conclusion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConclusion', array($conclusion));

        return parent::setConclusion($conclusion);
    }

    /**
     * {@inheritDoc}
     */
    public function getConclusion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConclusion', array());

        return parent::getConclusion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaTranscrito($fechaTranscrito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaTranscrito', array($fechaTranscrito));

        return parent::setFechaTranscrito($fechaTranscrito);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaTranscrito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaTranscrito', array());

        return parent::getFechaTranscrito();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCorregido($fechaCorregido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCorregido', array($fechaCorregido));

        return parent::setFechaCorregido($fechaCorregido);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCorregido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCorregido', array());

        return parent::getFechaCorregido();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAprobado($fechaAprobado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAprobado', array($fechaAprobado));

        return parent::setFechaAprobado($fechaAprobado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAprobado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAprobado', array());

        return parent::getFechaAprobado();
    }

    /**
     * {@inheritDoc}
     */
    public function setErrores($errores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setErrores', array($errores));

        return parent::setErrores($errores);
    }

    /**
     * {@inheritDoc}
     */
    public function getErrores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getErrores', array());

        return parent::getErrores();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncidencias($incidencias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncidencias', array($incidencias));

        return parent::setIncidencias($incidencias);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncidencias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncidencias', array());

        return parent::getIncidencias();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', array($observaciones));

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', array());

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecomendaciones($recomendaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecomendaciones', array($recomendaciones));

        return parent::setRecomendaciones($recomendaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecomendaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecomendaciones', array());

        return parent::getRecomendaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaRegistro($fechaRegistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaRegistro', array($fechaRegistro));

        return parent::setFechaRegistro($fechaRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaRegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaRegistro', array());

        return parent::getFechaRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEmpleado(\Minsal\SiapsBundle\Entity\MntEmpleado $idEmpleado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEmpleado', array($idEmpleado));

        return parent::setIdEmpleado($idEmpleado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEmpleado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEmpleado', array());

        return parent::getIdEmpleado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstadoDiagnostico(\Minsal\SimagdBundle\Entity\ImgCtlEstadoDiagnostico $idEstadoDiagnostico = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstadoDiagnostico', array($idEstadoDiagnostico));

        return parent::setIdEstadoDiagnostico($idEstadoDiagnostico);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstadoDiagnostico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstadoDiagnostico', array());

        return parent::getIdEstadoDiagnostico();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdLectura(\Minsal\SimagdBundle\Entity\ImgLectura $idLectura = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdLectura', array($idLectura));

        return parent::setIdLectura($idLectura);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdLectura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLectura', array());

        return parent::getIdLectura();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPatronAplicado(\Minsal\SimagdBundle\Entity\ImgCtlPatronDiagnostico $idPatronAplicado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPatronAplicado', array($idPatronAplicado));

        return parent::setIdPatronAplicado($idPatronAplicado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPatronAplicado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPatronAplicado', array());

        return parent::getIdPatronAplicado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRadiologoAprueba(\Minsal\SiapsBundle\Entity\MntEmpleado $idRadiologoAprueba = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRadiologoAprueba', array($idRadiologoAprueba));

        return parent::setIdRadiologoAprueba($idRadiologoAprueba);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRadiologoAprueba()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRadiologoAprueba', array());

        return parent::getIdRadiologoAprueba();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUserMod(\Application\Sonata\UserBundle\Entity\User $idUserMod = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUserMod', array($idUserMod));

        return parent::setIdUserMod($idUserMod);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUserMod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUserMod', array());

        return parent::getIdUserMod();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUserReg(\Application\Sonata\UserBundle\Entity\User $idUserReg = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUserReg', array($idUserReg));

        return parent::setIdUserReg($idUserReg);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUserReg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUserReg', array());

        return parent::getIdUserReg();
    }

    /**
     * {@inheritDoc}
     */
    public function addNotasDiagnostico(\Minsal\SimagdBundle\Entity\ImgNotaDiagnostico $notasDiagnostico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNotasDiagnostico', array($notasDiagnostico));

        return parent::addNotasDiagnostico($notasDiagnostico);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNotasDiagnostico(\Minsal\SimagdBundle\Entity\ImgNotaDiagnostico $notasDiagnostico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNotasDiagnostico', array($notasDiagnostico));

        return parent::removeNotasDiagnostico($notasDiagnostico);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotasDiagnostico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotasDiagnostico', array());

        return parent::getNotasDiagnostico();
    }

    /**
     * {@inheritDoc}
     */
    public function addDiagnosticoPendienteValidar(\Minsal\SimagdBundle\Entity\ImgPendienteValidacion $diagnosticoPendienteValidar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDiagnosticoPendienteValidar', array($diagnosticoPendienteValidar));

        return parent::addDiagnosticoPendienteValidar($diagnosticoPendienteValidar);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDiagnosticoPendienteValidar(\Minsal\SimagdBundle\Entity\ImgPendienteValidacion $diagnosticoPendienteValidar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDiagnosticoPendienteValidar', array($diagnosticoPendienteValidar));

        return parent::removeDiagnosticoPendienteValidar($diagnosticoPendienteValidar);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiagnosticoPendienteValidar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiagnosticoPendienteValidar', array());

        return parent::getDiagnosticoPendienteValidar();
    }

}
