<?php

namespace Proxies\__CG__\Minsal\SeguimientoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SecDetallesolicitudestudios extends \Minsal\SeguimientoBundle\Entity\SecDetallesolicitudestudios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'id', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'indicacion', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'observacion', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'fechahorareg', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'idempleado', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'idestablecimiento', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'idestablecimientoexterno', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'estadodetalle', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'idexamen', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'idusuarioreg', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'idsolicitudestudio');
        }

        return array('__isInitialized__', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'id', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'indicacion', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'observacion', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'fechahorareg', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'idempleado', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'idestablecimiento', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'idestablecimientoexterno', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'estadodetalle', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'idexamen', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'idusuarioreg', '' . "\0" . 'Minsal\\SeguimientoBundle\\Entity\\SecDetallesolicitudestudios' . "\0" . 'idsolicitudestudio');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SecDetallesolicitudestudios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndicacion($indicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndicacion', array($indicacion));

        return parent::setIndicacion($indicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndicacion', array());

        return parent::getIndicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', array($observacion));

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', array());

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechahorareg($fechahorareg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechahorareg', array($fechahorareg));

        return parent::setFechahorareg($fechahorareg);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechahorareg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechahorareg', array());

        return parent::getFechahorareg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdempleado(\Minsal\SiapsBundle\Entity\MntEmpleado $idempleado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdempleado', array($idempleado));

        return parent::setIdempleado($idempleado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdempleado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdempleado', array());

        return parent::getIdempleado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdestablecimiento(\Minsal\SiapsBundle\Entity\CtlEstablecimiento $idestablecimiento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestablecimiento', array($idestablecimiento));

        return parent::setIdestablecimiento($idestablecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestablecimiento', array());

        return parent::getIdestablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdestablecimientoexterno(\Minsal\SiapsBundle\Entity\CtlEstablecimiento $idestablecimientoexterno = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestablecimientoexterno', array($idestablecimientoexterno));

        return parent::setIdestablecimientoexterno($idestablecimientoexterno);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestablecimientoexterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestablecimientoexterno', array());

        return parent::getIdestablecimientoexterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadodetalle(\Minsal\SiapsBundle\Entity\CtlEstadoServicioDiagnostico $estadodetalle = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadodetalle', array($estadodetalle));

        return parent::setEstadodetalle($estadodetalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadodetalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadodetalle', array());

        return parent::getEstadodetalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdexamen(\Minsal\SiapsBundle\Entity\MntAreaExamenEstablecimiento $idexamen = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdexamen', array($idexamen));

        return parent::setIdexamen($idexamen);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdexamen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdexamen', array());

        return parent::getIdexamen();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuarioreg(\Application\Sonata\UserBundle\Entity\User $idusuarioreg = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuarioreg', array($idusuarioreg));

        return parent::setIdusuarioreg($idusuarioreg);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuarioreg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuarioreg', array());

        return parent::getIdusuarioreg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsolicitudestudio(\Minsal\SeguimientoBundle\Entity\SecSolicitudestudios $idsolicitudestudio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsolicitudestudio', array($idsolicitudestudio));

        return parent::setIdsolicitudestudio($idsolicitudestudio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsolicitudestudio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsolicitudestudio', array());

        return parent::getIdsolicitudestudio();
    }

}
